name: goliath

services: 
  auth: 
    build: 
      context: auth
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 5001
    container_name: auth_service
    restart: on-failure
    ports:
      - "5001:5001"
    volumes: 
      - ./auth:/app
    depends_on:
      - mysql
      - redis
    networks:
      - service_network

  image_processor:
    build: 
      context: image
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 5002
    container_name: image_processor_service
    restart: on-failure
    ports:
      - "5002:5002"
    volumes: 
      - ./image:/app
    networks:
      - service_network

  redis: 
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=redis
      - REDIS_PORT=6379
      - REDIS_DATABASES=2
    networks:
      - service_network

  mysql:
    image: mysql:8.0.34
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: p3
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    networks:
      - service_network

  gateway:
    build: 
      context: gateway
      dockerfile: Dockerfile
    container_name: gateway
    ports:
      - "3000:80"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth
      - image_processor
    networks:
      - service_network

  db:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
  api:
      build: ./flask
      ports:
        - 5000:5000
      depends_on:
        - db

networks:
  service_network:
    driver: bridge

volumes:
  postgres_data: